### ISSUE TITLE
Feedback from Reactabular project

### ISSUE THREAD

**Issue by bebraw** [interactivethings/catalog#126]
Hi,

I got linked to your project by @jantimon so I decided to give it a go as I needed to modernize the [documentation of Reactabular](https://bebraw.github.io/reactabular/). It worked out mostly fine. There are a couple of problems, though. Some of those might be due to my custom setup. I've listed the main ones below:
- The main bundle is huge - 1.8 MB. It's probably pulling in something it shouldn't. I'll try analyzing webpack stats later to get a better idea. Getting that to 500k range would be better. It would be even better to do a static `index.html` per each route and then load the rest dynamically. That's not easy to pull off, though.
- The code examples get mangled. I guess this is because I'm running React in production mode, there's uglify etc. so that could easily break it.
- I'm not sure how to pull code (string) and an example to a page like [sorting](https://bebraw.github.io/reactabular/#/how-to/sort) at the same time. I have a rough idea how to pull this off, but just thought you might have a better idea.
- I failed to find a nice way to hack on the main layout of the site. Instead I ended up defining `CustomPage` but obviously that doesn't work with the pages relying on Markdown.
- The Markdown setup discussed at the docs (pure path) didn't work so I had to go through a `require` instead. Maybe this had something to do with the fact that my paths were in form `../README.md` (outside of the source directory). This could easily be it if you are relying on a `require.context` (didn't check).

Overall Catalog is a promising tool already even if it has some shortcomings.

**Comment by herrstucki** [comment]
Thanks for the feedback @bebraw! I'll get back to you with a detailed answer as soon as possible.

**Comment by bebraw** [comment]
I pushed everything I could to a vendor bundle. Results:

```bash
Hash: 47f63974f7c2b3206489
Version: webpack 1.13.1
Time: 50851ms
                          Asset       Size  Chunks             Chunk Names
 bundle.de264190b1952762b2ef.js     330 kB       0  [emitted]  app
vendors.508b9d596eb2aa6f02bf.js    1.67 MB       1  [emitted]  vendors
                     index.html  359 bytes          [emitted]
   [0] multi vendors 268 bytes {1} [built]
    + 792 hidden modules
```

I also check out the stats. Looks like Babel runtime contributes about half. #100 might fix that.

I think I can squeeze another 100k by aliasing react-lite to react. I'll try that next.

**Comment by bebraw** [comment]
One more thing. The code examples suffer from the amount of data I am passing to them (it's a data driven component). Example:

![screenshot 2016-06-20 20 25 48](https://cloud.githubusercontent.com/assets/166921/16203927/447aa00c-3725-11e6-975c-e7f31b6d602a.png)

**Comment by herrstucki** [comment]
Okay, these are a few things at once, I'll try to address them as good as I can.

##### 1. Bundle Size

Bundle size is definitely an issue I wanted to address with #100, but I haven't tested the Bublé version in a real life project yet (some things may break).

The culprit is definitely babel-standalone which is 649K on its own. I'm not sure why the rest of the bundle's so big, the minified standalone version of Catalog without babel-standalone but including React and React Router is 542K. I suppose you're also bundling your own app's dependencies in your vendor file.

One trick you could try is to specify `babel-standalone` as an external in your webpack config and just not load it.

That said, creating the most efficient bundle hasn't been a top priority so far. Static rendering (#104) and splitting Catalog into smaller modules would probably help.

##### 2. Mangled code

Yes, this is a drawback of passing a minified React element to `<ReactSpecimen>` directly. If you specify the code example as a string, all your formatting gets preserved (you need babel-standalone in the bundle however). E.g.

```js
<ReactSpecimen>{`<MyAwesomeComponent />`}</ReactSpecimen>
```

or in a Markdown file:

    ```react
    <MyAwesomeComponent />
    ```

(for this to work, you need to import your component in the catalog config, e.g. `{title: 'Foo', path: 'foo', imports: {Foo}, component: FooDocs}`, see the [example](https://github.com/interactivethings/catalog/blob/master/examples/catalog-module/index.js))

##### 3. Layout hacking

Changing the layout fundamentally is not really something on the radar. There is a `theme` config option which is undocumented at the moment, where you can change [fonts, colors and stuff](https://github.com/interactivethings/catalog/blob/master/src/DefaultTheme.js). Use at your own risk though 😄  . Is there something particular you wanted to achieve?

##### 4. Markdown as `src`

To load Markdown files with `src` only works if you serve them from the specified path. They just get loaded in the browser, so they need to be somewhere (e.g. use webpack's file loader).

I'm not sure what exactly you mean with "I'm not sure how to pull code (string) and an example to a page like sorting at the same time" …

Thanks again for your feedback. It's great to hear from people using Catalog, and we want to make sure it also works for others than us. I realize a lot of these issues are because the documentation is lacking (which is kinda ironic since Catalog is a documentation tool 😅 ). We'll try to do a better job in the future!

**Comment by herrstucki** [comment]
Regarding documenting React components, I recommend to try doing it in a Markdown document instead of using `<Page>`. Formatting will be much nicer and it's less fiddling with markup. See

- https://interactivethings.github.io/catalog/#/specimens/react
- https://github.com/interactivethings/catalog/blob/master/examples/catalog-module/components/Foo/Foo.docs.md

**Comment by bebraw** [comment]
> The culprit is definitely babel-standalone which is 649K on its own. I'm not sure why the rest of the bundle's so big, the minified standalone version of Catalog without babel-standalone but including React and React Router is 542K. I suppose you're also bundling your own app's dependencies in your vendor file.

Yeah, there's lodash etc. I managed to bring down the size a bit but there might be more to do. Good point on treating `babel-standalone` as external. That's likely worth a go.

> 2. Mangled code

Yup. I guess pushing the code to imports will help here.

I wonder if there would be a smarter way to do the code extraction, though. On an earlier project I went through [a custom webpack loader](https://github.com/survivejs-demos/react-demos/blob/master/loaders/content.js) that I invoke like `'raw!../loaders/content!.'`. That will give me the source of a JSX file which I can then format etc. If I remember right, webpack might have something (`!!` or some trick) to achieve to the same without a dummy loader like that.

> Changing the layout fundamentally is not really something on the radar. There is a theme config option which is undocumented at the moment, where you can change fonts, colors and stuff. Use at your own risk though 😄 . Is there something particular you wanted to achieve?

I'm doing basically

```jsx
const CustomPage = ({ children }) => (
  <Page>
    <Fork className="right" project="bebraw/reactabular" />
    {children}
  </Page>
);
```

so if there was a hook for injecting something to the global layout, that would be enough for me.

> To load Markdown files with src only works if you serve them from the specified path. They just get loaded in the browser, so they need to be somewhere (e.g. use webpack's file loader).

Ok, that makes perfect sense now. My directory has documentation outside of the documentation root so that's problematic for a scheme like this. Now that I think of it, setting up some aliases might work here.

> I'm not sure what exactly you mean with "I'm not sure how to pull code (string) and an example to a page like sorting at the same time" …

Here's some [context](https://bebraw.github.io/reactabular/#/how-to/sort). The page is pretty useless without code. I guess I'll try the trick I mentioned above and push the code to a separate file which I then process.

> Regarding documenting React components, I recommend to try doing it in a Markdown document instead of using <Page>. Formatting will be much nicer and it's less fiddling with markup. See

Yeah. That could work.

Thanks again! Feel free to close this issue or split into smaller ones as you see fit. 👍

**Comment by herrstucki** [comment]
Regarding customization, I think #125 might be the right direction for something like what you want to do. Then you can wrap `<Catalog />` in your own layout and add stuff like the fork badge. Of course, you can also do that the old-school way and add that element in your `index.html` 😁

**Comment by herrstucki** [comment]
Regarding extracting code from JS files: I don't think that's a concern of Catalog. You can do whatever you want with custom webpack loaders etc. and import the results as you like. I prefer to keep everything in Markdown files. For your example at https://bebraw.github.io/reactabular/#/how-to/sort something like this or similar should work:

    ```react
    state:
      data: [...]
      columns: [...]
      sortingColumns: null
    ---
    const sorter = sort.byColumns; 
    const sortedData = sorter.sort(state.data, state.sortingColumns, orderBy);

    <Table columns={columns} data={sortedData}>
      <Table.Header />
      <Table.Body rowKey="id" />
    </Table>
    ```

I'm probably missing some details here 😄 . Again, a good reference for this is https://github.com/interactivethings/catalog/blob/master/examples/catalog-module/

**Comment by bebraw** [comment]
Cool. I'll try more Markdown driven approach. 👍 

When it comes to customization, wrapping `<Catalog />` could do the trick.

If you want more visibility for the project (more users, yay), I could set up an interview for you at [SurviveJS](http://survivejs.com/). Let me know if you are interested.

**Comment by bebraw** [comment]
Is it possible to fetch code from a file within Markdown? I have problematic pages like [how to highlight](https://bebraw.github.io/reactabular/#/how-to/highlight-search) where I had to copy/paste code manually. That's somewhat brittle.

I've also noticed that sometimes the code can fail silently. The code will show up but the example doesn't.  I can set up a specific example if you want.

Ideally that `<HighlightTable />` should go away if the code worked. Note that I need to retain the imports so the users know where to find them but obviously Babel will choke on that.

I guess it would be even better to integrate something like CodeMirror to allow modifying the code. Since there's a Babel runtime already, leaping to that wouldn't take much. [Component Playground](https://github.com/FormidableLabs/component-playground) does this and in my experience it works well.

Let me know if you need further info.

**Comment by naehrstoff** [comment]
In order to get code into Catalog (and have it linted, too, as per issue #139), a possibility would be to add a Markdown generation step, i.e. use Markdown as a template that you fill content into using a pre-processor like Node, PHP, Ruby, whatever. This is a powerful technique that we have used many times. It is one of the core principles behind Catalog that it should not depend on a specific build technology (because they always change), but work with a simple API (which is Markdown in this case). And this API can be generated.

Here's an example for Ruby's `erb`:

    # Generated Markdown

    Just include the contents of a file:

    ```code
    <%= puts File.read('code-example.js') %>
    ```

**Comment by herrstucki** [comment]
I'm closing this for now, as I don't see any immediate action. Feel free to re-open with more details.
