### ISSUE TITLE
Allow custom presets/plugins to be passed to babel-standalone

### ISSUE THREAD

**Issue by bebraw** [interactivethings/catalog#135]
I rely on `syntax-object-rest-spread` and `transform-object-rest-spread` at Reactabular docs. It would be good if you could pass custom plugins to `babel-standalone` somehow (root configuration?).

**Comment by herrstucki** [comment]
The stage-2 preset is enabled, so object-rest-spread should work?

**Comment by bebraw** [comment]
Ah, good point. Still, possibly good feature to have as you never know what kind of plugins people are using.

The problem is that I've been seeing these silent failures. I wonder if there's a way to get more debug output out of `babel-standalone`.

**Comment by herrstucki** [comment]
Babel compilation errors of React Specimens should display right in the specimen itself (instead of the rendered output), so silent errors are probably happening somewhere else. Anyway, it's a bit difficult to fix this without further details.

Also, I'm not sure that we should support babel-specific configuration options to enable experimental language features. Catalog is a _documentation_ tool, and one could argue that it's better not to use these features when documenting code.
