### ISSUE TITLE
Add anchors to headers generated based on Markdown

### ISSUE THREAD

**Issue by bebraw** [interactivethings/catalog#137]
This would make it possible to link to specific sections of documentation pages easily. That's quite vital when you want to point to a specific portion (good for linking).

**Comment by bebraw** [comment]
If you want reference, [here's how you can pull it off with marked](https://github.com/survivejs/site/blob/master/utils/markdown.js).

**Comment by herrstucki** [comment]
Yeah, good point. Although it won't be usable with hash-based routing, I guess it wouldn't hurt to add anchors.

**Comment by herrstucki** [comment]
Also see #28 for context.

**Comment by bebraw** [comment]
Ah, true. Still, quite vital.

Have you tried [404.html based routing](http://www.backalleycoder.com/2016/05/13/sghpa-the-single-page-app-hack-for-github-pages/) by the way?

**Comment by naehrstoff** [comment]
I would love to be able to link to sections within a document, could have needed it several times so far. Currently, I don't see how we can solve this nicely due to the hash-based routing.

404-based routing is not feasible as a default, as Catalog should decidedly not depend on a specific server configuration. And if you have a server you can actually just do pushState routing.

Two ideas for how to solve this:

1. Just add the anchors and require pushState routing to be able to make use of them
2. Use a custom router that allows the use of anchors. For hash based routes it could do something like `path#catalog/route?anchor=abc` while for pushState routing it would work like `path/catalog/route#abc`. I fear that this adds much complexity.

Let's add the anchors as a first step and take it from there, I guess 😃

**Comment by herrstucki** [comment]
I'm working on a solution (currently mostly in my head) for this.

The tricky part is that pages get rendered asynchronously, and even with pushstate routing the page doesn't automatically jump to the relevant part because it's not there on page load. With static rendering this would work but we have to find a solution which works without it.

Another important aspect is that I want internal links to look the same (i.e. `[/foo#bar](see Bar)`), regardless of the type of history and the resulting URL (which could look like `/#/foo?anchor=bar` or `/foo#bar`).

**Comment by bebraw** [comment]
Maybe you need to solve this using a react-router hook. Once you know a page has loaded, scroll to the section.
