### ISSUE TITLE
Unknown prop warning in React 15.2.0

### ISSUE THREAD

**Issue by bebraw** [interactivethings/catalog#142]
Hi,

I'm seeing

```
(program):44 Warning: Unknown prop `_radiumDidResolveStyles` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by StyleRoot)
    in StyleRoot (created by App)
    in App (created by ConfiguredCatalogContext)
    in CatalogContext (created by ConfiguredCatalogContext)
    in ConfiguredCatalogContext (created by RouterContext)
    in RouterContext (created by Router)
    in ScrollBehaviorContainer (created by Router)
    in Router
```

on React 15.2.0 at [my project](https://github.com/bebraw/reactabular) and Catalog 2.2.9. Something near `StyleRoot` is leaking a prop most likely.

**Comment by bebraw** [comment]
I can actually see this if I clone Catalog locally and then run `make`. It's the same error. So you can test it against that. Just make sure you have a fresh version of React.

**Comment by naehrstoff** [comment]
I get this as well. Seems to be due to this change in React: https://github.com/facebook/react/commit/de1de9e18f8faf153ad673c8206a2918e3e81035 which is more clearly described in https://facebook.github.io/react/warnings/unknown-prop.html

I just checked and the latest version of Radium is from March, so I guess we just have to wait for this to get resolved in Radium.

**Comment by bebraw** [comment]
Related issue if you want to track, https://github.com/FormidableLabs/radium/issues/759 .

**Comment by naehrstoff** [comment]
Thanks, subscribed 😄

**Comment by herrstucki** [comment]
I'm closing this, since there's not really something we can do about it until Radium publishes a fixed version.
