### ISSUE TITLE
Add arbitrary classes to specimen content

### ISSUE THREAD

**Issue by herrstucki** [interactivethings/catalog#15]
@piotrf and I were discussing that it'd be useful to add arbitrary classes to specimens. The particular use-case is that we need to simulate a body class each specimen is wrapped in. Currently we can do two things:

* `<body class="my-body-class">` in the document where Catalog runs. This might break Catalog's own styles though.
* Manually wrapping each specimen's code in `<div class="my-body-class">...</div>`. This seems more "correct" but it's tedious and it adds noise to the specimen's source view.

We've already discussed something similar in #5.

Ideally, we could write:

    ```html|dark,my-class
    …
    ```

which would output

```html
<div class"cg-Specimen-Html-content cg-Specimen-Html-content--dark my-class">…</div>
```

The way to decide if this particular class should be namespaced or not would be to check against the defined modifiers (plus `run-script`).

I don't feel super-excited about this approach. Ultimately I still think, all specimens should be iframed dynamically, so we can encapsulate their styles properly.

**Comment by herrstucki** [comment]
Alternative syntaxes for specimen options:

1. `html.my-class.another-class|dark` (add classes to the specimen type)
2. `html|dark|my-class` (add third section for classes)
3. `html|dark,.my-class` (prefix classes with `.` in the options)

**Comment by herrstucki** [comment]
Another option would be to specify this in the Catalog configuration. But what if we want to show specimens embedded in different body classes (e.g. for themed UIs)?

I'm unsure if introducing new special syntax for this case is really a good idea. The best solution may still be to wrap each specimen in `<div class="my-body-class">...</div>`. This has the advantage that it's very obvious how the code should be structured (because it also shows up in the source view), especially in the case of multiple themes.

**Comment by naehrstoff** [comment]
I would prefer not to add special syntax like this but to keep the API simple: `specimen|modifiers`. However, there are two ways forward that I think are reasonable (and not mutually exclusive) and that can solve this problem for similar situations:

1. All specimen types should really be plugins and Catalog should be extensible through configuring custom plugins in the setup. This will allow us to create plugins tailored to very specific usecases instead of trying to shoehorn a very general approach into the default plugins.
2. All components should iframeable. There were some issues with our first approach (https://github.com/interactivethings/catalog/issues/4), but it should be doable and would resolve issues relating to positioning elements.

In this specific case, using Middleman app as a backend, we were able to solve this problem by using a helper that wraps every partial we wanted to add in a `<div>` with the required class.

Closing this issue unless there are further comments.
