### ISSUE TITLE
Margin-left for lists

### ISSUE THREAD

**Issue by wiederkehr** [interactivethings/catalog#16]
List should be indented by a margin on the left side.
This is true for text in specimens as well as outside.

![screen shot 2015-02-19 at 16 56 47](https://cloud.githubusercontent.com/assets/15137/6270185/68450420-b858-11e4-9e34-dcfa383b13ef.png)

![screen shot 2015-02-19 at 16 57 48](https://cloud.githubusercontent.com/assets/15137/6270198/81a66256-b858-11e4-961e-cf493c33fbc4.png)

**Comment by naehrstoff** [comment]
This is actually intentional as per http://www.markboulton.co.uk/journal/five-simple-steps-to-better-typography-part-2 and others.

The lists were indeed indented in the first versions, and it looked fine for simple designs. Unfortunately, it fell apart quickly when more complex text structures were created and resulted in an unaesthetic wave-form with holes. The initial designs also had orange bullet points, which accentuated the problem.

We can definitely think about introducing the left margin again, but it should be done in the Catalog test page, not in a static design software, so that we see how it looks like when mixed within paragraphs, headings and stuff. It might also be a good idea to add some more test cases to find a balanced design. The overall goal should be to keep Catalog's styling as calm as possible to let the actual components stand out, I think.

**Comment by herrstucki** [comment]
Changed and approved by @chrizskenda :smile:
