### ISSUE TITLE
React 15.3.0 - "Couldn’t render specimen: SyntaxError"

### ISSUE THREAD

**Issue by bebraw** [interactivethings/catalog#170]
I tried updating my project to React 15.3.0. This resulted in `Couldn’t render specimen: SyntaxError: Duplicate parameter name not allowed in this context`. I can also see `
warning.js?0260:44Warning: You are manually calling a React.PropTypes validation function for the `content` prop on `PageRenderer`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.` at the console.

If I fix React version to `15.2.1` I don't see the proptype warning anymore although Catalog output is still the same (feels like a version thing too, I'll debug this further).

Here's a [branch](https://github.com/reactabular/reactabular/tree/react-153) in case someone wants to verify/debug.

Just wondering if anyone else is seeing this or is it only me.

**Comment by bebraw** [comment]
Even

```jsx
const DragAndDropDemo = () => (<div>demo</div>);

<DragAndDropDemo />
```

kind of demo seems to fail for me with `Couldn’t render specimen: SyntaxError: Duplicate parameter name not allowed in this context` on React 15.2.1. This is weird as it definitely worked earlier.

**Comment by herrstucki** [comment]
You're [importing React into Catalog](https://github.com/reactabular/reactabular/blob/72033d24af1e536573898d8ec74bd9f556ef8ab4/docs/index.jsx#L61), which you don't need to do because it's already imported. All imports end up being passed as parameters to the transformed Specimen code function, so that's what goes wrong there (= "duplicate parameter name").

BTW, you can use `imports` at the top level config, so you don't need to repeat it on every page.

I can't reproduce the proptype warning …

**Comment by bebraw** [comment]
> You're importing React into Catalog, which you don't need to do because it's already imported. All imports end up being passed as parameters to the transformed Specimen code function, so that's what goes wrong there (= "duplicate parameter name").

That was it, thanks.

> BTW, you can use imports at the top level config, so you don't need to repeat it on every page.

Great, fixed that too.

> I can't reproduce the proptype warning …

I can link you to a production build later. It feels like something React 15.3 specific. They have been deprecating bits lately.
