### ISSUE TITLE
Catalog CLI

### ISSUE THREAD

**Issue by herrstucki** [interactivethings/catalog#22]
What about turning Catalog into a CLI tool and/or Node module.

That would have several benefits:

- Potential integration of a development server with hot module replacement
- No need for `index.html`
- Routes and navigation menu could be auto-generated through directory tree
- Wrapping Markdown files into React components could be done by simply concatenating, solving the problem we'd have with #21.
- Build to static site = better performance
- Catalog on the server = potential integration of an editor

**Comment by naehrstoff** [comment]
I like all the benefits this idea will provide a lot, under one condition: Catalog core needs to stay an independent stand-alone JS app that is only concerned with loading Markdown files. This design goal has proven very, very useful again and again, because it allowed us to use different backends (no backend whatsoever, Rails, Middleman, Node, …). In my view, not being tied to a specific backend technology is Catalog's greatest strenght, because it allows its use in all kinds of projects, from very small hand-coded index.html projects to huge projects with partials in the backend.

Regarding #21: if we can only get this to work through such a build step, I'd rather not have it, because some syntax will only work with this tool but not Catalog core.

But yes, having better tooling would be much appreciated (as long as it's optional (had to say that again :) ))

**Comment by herrstucki** [comment]
In progress at #50

**Comment by herrstucki** [comment]
The node module part is done. I'll keep the issue open for the CLI but it's not that much of a priority and not that straightforward depending on the documented project's setup.

**Comment by herrstucki** [comment]
Closing as there is no immediate need. For the case where we integrate Catalog into a React app, whatever build process is in place there should handle this.
