### ISSUE TITLE
function calls inside ReactSpecimen

### ISSUE THREAD

**Issue by Laurian** [interactivethings/catalog#261]
I'm using react-i18next, I have

```
<ReactSpecimen>
 <Button action={action}>{t('Primary button')}</Button>
</ReactSpecimen>
```

but in documentation it renders only as

```
<Button action={action}>Primary button</Button>
```

How can I have the documentation show the intended usage?

**Comment by herrstucki** [comment]
The problem is that ReactSpecimen in this case only "sees" the result of the function call; the source display is basically a stringification of the React Element that you pass in (that's why it never will look exactly how you typed it).

If you want verbatim source code display, you can pass a string to ReactSpecimen like this:

```jsx
<ReactSpecimen>
 {`<Button action={action}>{t('Primary button')}</Button>`}
</ReactSpecimen>
```

If you do that, you need to make sure that `Button`, `action` and `t` are [imported in the Catalog config](https://interactivethings.github.io/catalog/next/#/configuration?a=imports).
