### ISSUE TITLE
Linking to a Catalog page part

### ISSUE THREAD

**Issue by herrstucki** [interactivethings/catalog#28]
Currently, because we use hash history this isn't possible. We could switch to pushState-style routing but that would require a server which supports that.

**Comment by naehrstoff** [comment]
Difficult from a technical standpoint but essential from a users' perspective :)

This has been a very real problem in several projects, where we wanted to link from one section to another in order to guide the user. In larger projects there are tons of components, so we need to provide a way to make them accessible by linking stuff.

Bonus points for checking whether the links actually point to a valid, exisiting place or whether they go into the void … Dead links, the other problem encountered in documentation.

Could we do something like

```
Absolutely see the [red button](#interactive/elements/path:red-button) style
```

I know, ugly and such a secret special case with the colon. Let's brainstorm a better way.

**Comment by tpreusse** [comment]
I'd recommend to use a query string parameter – which react router already supports and parses.

Even if we later were to switch to push state routing this would continue to work and also be sent to the server where potential redirects of old / dead links could happen.

**Comment by herrstucki** [comment]
I prefer using a quasi-standard solution like the query string to inventing our own syntax here. Although I think it's really stupid that we can't just write `[my lovely buttons](/components#buttons)`

This would all not be a problem if catalog produced a static site as output :trollface:

**Comment by herrstucki** [comment]
Another point: we should turn internal links into `<Link>`s but not external ones.

**Comment by herrstucki** [comment]
When Catalog is integrated in a React app, it's up to the app to decide which routing strategy (browser or hash history) it uses. When using browser history, regular hashes can be used to jump to page parts. The only thing we'd need for that is to generate IDs on headings.

I'm closing this issue because I don't want to build some hacky solution for this which covers every possible use case. If a real need arises, feel free to reopen again.
