### ISSUE TITLE
including html snippets

### ISSUE THREAD

**Issue by jeaster12** [interactivethings/catalog#299]
Hi Team,

Looking around the docs pages and found this https://github.com/interactivethings/catalog/tree/gh-pages/docs/html-project-example - 
It looks like you may be able to include things like a data visualization. 
I'm not completely clear how to do this or if it's still supported?

Also for imports - could I use an html snippet by including it in a md page?
Fo instance if we have a snippet of say buttons thats straight html that is tested against - can I then include that snippet in a buttons.md documentation page?

Thanks!

**Comment by herrstucki** [comment]
Hi @jeaster12, we've removed this specimen type from Catalog core because we felt it was too specific and complex to maintain and ship per default. The extracted version lives at https://github.com/interactivethings/catalog-specimen-project, although I'm not completely sure about its status.

You can add the custom specimen like this:

```jsx
<Catalog
  specimens={{project: ProjectSpecimen}}
  /*...*/
/>
```

**Comment by herrstucki** [comment]
I'm closing this issue, please feel free to reopen if you run into trouble.
