### ISSUE TITLE
Custom inline HTML within Markdown files not rendering properly

### ISSUE THREAD

**Issue by dlewand691** [interactivethings/catalog#377]
I'd like to add custom HTML to my Markdown files, but it is rendered as regular text, not the actual HTML. I'm using it in a couple of instances:

1. Need to add a button to an external link and style it accordingly. 
1. Using a blockquote 
1. Use custom heading styling beyond the typical H1-6

Is it possible to do this **without** using a Specimen?

**Comment by dlewand691** [comment]
After doing more exploring, I discovered that if you wrap everything within an empty `<div>`, it works, but now `[object Object]` appears everywhere. If you minify the HTML, it works, but is not ideal.

Thoughts?

<img width="858" alt="screen shot 1" src="https://user-images.githubusercontent.com/1159913/36750087-a1ea17e6-1bca-11e8-9bff-d8dec474d980.png">

**Comment by herrstucki** [comment]
I'm not sure we want to support arbitrary HTML.

What you already _can_ do is use arbitrary React on pages when you create a `.js` page (instead of `.md`). For example:

```jsx
import {markdown} from 'catalog';

export default () => markdown`
# Markdown title

Markdown paragraph

${<div className="foo">Custom content!</div>}
`
```

or

```jsx
import {Page} from 'catalog';

export default () => <Page>
  <h1 className="foo">Custom h1</h1>
  <div className="bar">Custom content!</div>
</Page>
```

**Comment by dlewand691** [comment]
I guess I was assuming that the Markdown version being used supported basic HTML usage as well. Not sure what's being used, but I've always been a fan of [Markdown-it](https://markdown-it.github.io/), which supports a lot of essential elements to a style guide (footnotes, custom containers, typographic elements like superscript, subscript, etc etc etc).

The other reason for wanting to do this is for using elements from the style guide in the pages themselves... things like buttons and blockquotes. Some new specimen types I would recommend/request would be:

1. Button (with options for size, span, icon on left or right)
1. Basic content container to create multi-column layouts or in combination with other elements like code blocks
1. Video support for YouTube and Vimeo
1. This is a biggie: CLI for creating and adding new pages and sections. I'm currently using [Astrum](http://astrum.nodividestudio.com/#install) to build our style guide, but Catalog has a lot more power and better features. The best thing about Astrum is the CLI. [Take a look and see what you think](http://astrum.nodividestudio.com/#install), would be a big convenience. Our current style guide is [here](https://newuat.cognizant.com/styleguide/) for reference.

Anyways, thanks for creating Catalog! I've enjoyed using it immensely and will be porting everything over to it in the coming months. Will share any other feedback as I go.

**Comment by herrstucki** [comment]
@dlewand691, we use [marked](https://github.com/markedjs/marked) which supports HTML content _but_ we don't just create a HTML string from Markdown content but React elements. Allowing arbitrary HTML in the Markdown wouldn't work because we'd need to parse it first which I don't want to add. Otherwise, all HTML content would need to be inserted like this `<div dangerouslySetInnerHTML={{__html: html}} />` which is most certainly not the intended result because all HTML elements would be wrapped into a div (and it's unsafe).

As for your other requests:

1. I think a more generic button than the [Download Specimen](https://docs.catalog.style/specimens/download) makes sense, do you want to create a new issue for that?
2. That's going to be hard to express in plain Markdown. Again I recommend creating [custom pages using React](https://docs.catalog.style/guides/react)
3. Makes sense, can you add an issue?
4. This also deserves an issue and separate discussion.

I'm closing this issue, as I don't see it actionable in the near future. Feel free to add new issues for individual feature requests. Thanks!

**Comment by dlewand691** [comment]
Thanks for the input! Guess I'm asking it to do more than what it's capable (or should) do.  

I've opened the issues around the button and video specimens.

To clarify point #2, it would basically be a specimen that has a span option and contains generic content (markdown or otherwise) that could sit next to another specimen. For example: button specimen on the left, content specimen on the right that explains it.
