### ISSUE TITLE
Question: how do you theme Catalog?

### ISSUE THREAD

**Issue by drw158** [interactivethings/catalog#402]
I'm having some trouble figuring out how to theme catalog.

https://docs.catalog.style/configuration/theming

I have a default, fresh install of Catalog. Where do the options like `logoSrc`, `theme`, and `textColor` go? In `index.js`? If so, can you please show me how to do that or give me an example?

**Comment by herrstucki** [comment]
The docs are a bit confusing there 😅. If you change your configuration to this it will work:

```diff
ReactDOM.render(
  <Catalog
    title="Catalog"
    pages={pages}
    logoSrc={"https://cldup.com/URxYAZC6GQ.png"}
    sidebarColor={ {Text: "#ee0000"} }
    theme={
      {
        textColor: "#2e4453",
        background: "#f3f6f8",
        linkColor: "#0087be",
-       pageHeading: { Background: "#0087be", TextColor: "#0087be" }
+       pageHeadingBackground: "#0087be",
+       pageHeadingTextColor: "#0087be"
      }
    }
    />,
  document.getElementById("catalog")
);
```

For reference you can look at the [default theme](https://github.com/interactivethings/catalog/blob/bf38e278a94bd92cefa2ae52043592979f5f3e1f/src/DefaultTheme.js)

**Comment by drw158** [comment]
Thank you very much!

**Comment by justingolden21** [comment]
Honestly, just mentioning

```
ReactDOM.render(
  <Catalog
    title="Catalog"
    pages={pages}
    theme={
      {
        textColor: "#2e4453",
    // ...
```

with a link to https://github.com/interactivethings/catalog/blob/master/src/DefaultTheme.js

is good enough for the [docs](https://docs.catalog.style/configuration/theming) in my opinion

I just didn't know **where** to add all of the theme stuff and needed a reference. Once I knew to add it to `index.js` inside `ReactDOM.render` and I had the default theme as a reference it was cake, and I think others will be able to follow similar logic. I was just confused because I didn't know what properties to update where.
