### ISSUE TITLE
CSS of catalog leaks into the React specimens

### ISSUE THREAD

**Issue by wereHamster** [interactivethings/catalog#75]
I've just had the issue that the react components in catalog didn't look exactly like the ones in the web app. The reason was because Catalog sets `text-rendering: optimizeLegibility; -webkit-font-smoothing: antialiased;` on the body element, and our web app doesn't. Is it possible to completely shield the react specimens from the page CSS? Perhaps using Shadow DOM (http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/#toc-style-scoped)?

**Comment by naehrstoff** [comment]
We at one point discussed using iframes for this. @herrstucki was an advocate of that technique, I don't know what his current opinion is.

I myself believe that Catalog should just take care to not override stuff that doesn't concern it. And coming from the other direction: overriding enough stuff so that it can work even when there's a CSS reset in place.

In any case: Catalog should not take advantage of the most cutting edge technologies because we need to be able to use it also with less powerful browsers.

**Comment by herrstucki** [comment]
I removed the global text rendering styles. While this fixes the immediate problem, it doesn't solve the fundamental issue but I don't think there's a good solution now.

Shadow DOM _could_ be a solution but I agree with @naehrstoff that it's way too early to use it. As far as I know, the spec hasn't settled yet, and [very few browsers](http://caniuse.com/#search=shadow+dom) support it.

From a style scoping standpoint, Iframes are a pretty good solution but we'd need to find a way to make them auto-scale to fit their contents (there's a very old issue on that at #4). I had a proof-of-concept at one point but didn't pursue it further. Let's see if this is really worth to tackle in the future.
